site_name: Proyecto Final


theme: flatly

plugins:
    - search
    - markdownextradata: {}


nav:
    - Overview: index.md
    - GUI: gui.md
    - LEX:
        - Lex API: lex.md
        - LMR: lmr.md
        - Cozmo: cozmo.md
    - Examples: examples.md

