site_name: Proyecto Final


theme: flatly

plugins:
    - search
    - markdownextradata: {}


nav:
    - Overview:
        - Intructions: index.md
        - Getting Started: getting_started.md
    - GUI: gui.md
    - LEX:
        - Lex API: lex.md
        - LMR: lmr.md
        - Cozmo: cozmo.md

    - Extras:
        - A gift to you: agift.md
        - Redis: redis.md
        - Puntos Extras: extras.md

